function randomSituatie(){
    const situatieZinnen = [
        "Jij krijgt voor je verjaardag een ",
        "Je droomt over een ",
        "Je trouwt later met een ",
        "Je bent verliefd op een ",
        "Je bent doodsbang voor een ",
        "Je speelt verstoppertje met een ",
        "Voor je verjaardag wil jij een ",
        "Je wilt urenlang dansen met een ",
        "Jouw favoriete avatar is een ",
        "Je staat op het punt om te werken aan een ",
        "Je koestert de hoop om naast een te slapen ",
        "Je voelt de drang om te bellen met een ",
        "Je ziet jezelf zwemmen met een ",
        "Je bent gefascineerd door het idee om te dineren met een ",
        "Je voelt een onweerstaanbare drang om te schilderen met een ",
        "Je verlangt intens naar een knuffel met een ",
        "Je ziet jezelf uitbundig feesten met een ",
        "Je droomt ervan om foto's te maken met een ",
        "Je overweegt om een dutje te doen naast een ",
        "Je voelt de roep om les te geven aan een ",
        "Je kijkt uit naar winkelen met een ",
        "Je bent vastbesloten om spellen te spelen met een ",
        "Je voelt de inspiratie om muziek te maken met een ",
        "Je ziet jezelf genieten van films met een ",
        "Je bent van plan om een taart te bakken voor een ",
        "Je fantaseert over reizen naar de maan met een ",
        "Je droomt van tijdreizen met een ",
        "Je verbeeldt jezelf Atlantis te ontdekken met een ",
        "Je ziet jezelf tikkertje te spelen met een ",
        "Je overweegt om yoga te doen met een ",
        "Je verdiept jezelf in boeken over een ",
        "Je droomt ervan om grapjes te maken met een ",
        "Je ziet jezelf de polonaise te dansen met een ",
        "Je overweegt om op een eenwieler te rijden naast een ",
        "Je voelt de drang om te vechten tegen een ",
        "Je plant om naar de markt te gaan met een ",
        "Je voelt de aantrekkingskracht om te picknicken met een ",
        "Je overweegt om zandkastelen te bouwen naast een ",
        "Je bent van plan om wedstrijdjes te doen met een ",
        "Je verlangt naar knutselen met een ",
        "Je bent vastbesloten om op avontuur te gaan met een ",
        "Je voelt de inspiratie om te klimmen in een boom naast een ",
        "Je ziet jezelf racen naast een ",
        "Jij wenst al je hele leven te ",
        "Jij gaat morgen dansen met ",
        "Jij droomt van volgende week ",
        "Jij hoopt ooit te ",
        "Jij plant binnenkort een ",
        "Jij verlangt al tijden naar ",
        "Jij fantaseert over ",
        "Jij voorspelt dat je snel ",
        "Jij wenst al een eeuwigheid te ",
        "Jij verlangt naar ",
        "Jij kijkt uit naar ",
      ];

      const bijvoeglijkeNaamwoordenArray = [
        "glimmende ",
        "dappere ",
        "knorrige ",
        "wilde ",
        "schattige ",
        "sprankelende ",
        "lachende ",
        "huilende ",
        "dromerige ",
        "donzige ",
        "knusse ",
        "fluisterende ",
        "schaterende ",
        "grimmige ",
        "stuurse ",
        "golvende ",
        "knisperende ",
        "twinkelende ",
        "buitengewone ",
        "prikkelende ",
        "zwevende ",
        "knetterende ",
        "pruttelende ",
        "spetterende ",
        "spookachtige ",
        "piepende ",
        "ratelende ",
        "dwarrelende ",
        "sprankelende ",
        "tintelende ",
        "rillende ",
        "schrikbarende ",
        "sissende ",
        "verleidelijke ",
        "bubbeldende ",
        "verstijfde ",
        "knuffelige ",
        "rollende ",
        "kleurrijke ",
        "fonkelende ",
        "stekende ",
        "spinnende ",
        "knapperige ",
        "glinsterende ",
        "knisperende ",
        "sissen ",
        "knetterende ",
        "schitterende ",
        "blikkerende ",
        "flitsende ",
        "ronkende "
      ];

      const zelfstandigeNaamwoordenArray = [
        "ster",
        "leeuw",
        "bloem",
        "regenboog",
        "vogel",
        "droom",
        "wolk",
        "kat",
        "hond",
        "beer",
        "boom",
        "zee",
        "rivier",
        "berg",
        "zon",
        "maan",
        "sterren",
        "schat",
        "eiland",
        "schelp",
        "storm",
        "vuur",
        "ijs",
        "wind",
        "roos",
        "rozen",
        "sneeuw",
        "licht",
        "schaduw",
        "kasteel",
        "draak",
        "fee",
        "prinses",
        "prins",
        "held",
        "avontuur",
        "fantasie",
        "magie",
        "toverstaf",
        "sprookje",
        "dans",
        "melodie",
        "muziek",
        "liefde",
        "vriendschap",
        "geluk",
        "diamant",
        "juweel",
        "kaboutersokken",
        "pizzapunt",
        "vliegende koe",
        "snottebel",
        "stuiterbal",
        "badeend",
        "knuffelbeer",
        "sproetenmonster",
        "bananenschil",
        "goudvis",
        "hamsterwiel",
        "badeend",
        "koekjesmonster",
        "eenhoorn",
        "spinnenweb"
      ];

      const inleiding = 
      "In de gloed van het avondlicht, verschijnt daar een mysterieuze figuur, gehuld in de nevels van tijdloze wijsheid. \nDeze sprookjesachtige wezen, bekend als de Wijze van de Eeuwige Gedachten, kent de diepten van je ziel als geen ander. \nMet een blik die dwars door de schijnbare grenzen van tijd en ruimte snijdt, \nonthult deze figuur verborgen verlangens, fluisteringen van hoop en de stiltes van je diepste angsten. En dat is... ";


    const randSitu = situatieZinnen[Math.floor(Math.random() * (situatieZinnen.length)+1)];
    //console.log(randSitu);
    const randBijv = bijvoeglijkeNaamwoordenArray[Math.floor(Math.random() * (bijvoeglijkeNaamwoordenArray.length) +1)];
    //console.log(randBijv);
    const randNmw = zelfstandigeNaamwoordenArray[Math.floor(Math.random() * (zelfstandigeNaamwoordenArray.length) + 1)];
    //console.log(randNmw);

    console.log(inleiding + `\n` + randSitu + randBijv + randNmw + '!')   
};

randomSituatie()